### ISSUE TITLE
Major version 3.0.0

### ISSUE THREAD

**Issue by tvbeek** [pdepend/pdepend#702]
## Description
We are getting more concrete plans for a new major version.

## Tasks for the new major version

- [ ] Drop old PHP versions
- [ ] Clean up syntax where possible .
- [ ] Upgrade used tools.
- [ ] Decide if an upgrade guide is needed or only a release with changelog.
- [ ] Add option to get last V2 phar file from website.
- [ ] Review and merge existing PR's with breaking changes. https://github.com/pdepend/pdepend/pulls?q=is%3Aopen+is%3Apr+milestone%3A3.0.0

## Remove deprecations
- [ ] Other deprecations?

**Comment by ravage84** [comment]
We  set up  some pages for the new major version 3.0 in the repo wiki:

- [3.0-Goals](https://github.com/pdepend/pdepend/wiki/3.0-Goals)
- [3.0-Ideas](https://github.com/pdepend/pdepend/wiki/3.0-Ideas)
- [3.0-Roadmap](https://github.com/pdepend/pdepend/wiki/3.0-Roadmap)

**Comment by AJenbo** [comment]
I made PRs for dropping the rest of the unsupported PHP versions. In total that will get us to 5000 lines removed since 2.x.

I also made one for removing things marked as deprecated, except for two functions that are still used internally.

Settling on a code styles and which tool to use for it should be the next step I think. Having that cleared up will make cleaning up syntax a lot easier.

I think it could be good to have 3.x out by the time PHP 8.4 arrives (November 2024).

I would also like to get the project to pass PHPStan level 9 by then, I think it's a doable target and we are a bit more free as to how to approach it during the 3.x cycle.

**Comment by glo71317** [comment]
@tvbeek @AJenbo Could we be planning to release the major version sooner, considering that PHP 8.4 has been out for almost two months now?

**Comment by AJenbo** [comment]
We need to land parallel processing,  work should resume next week

**Comment by Axent96** [comment]
@AJenbo any plan for release date? the change is already present, or?

**Comment by AJenbo** [comment]
I'm not in charge of releases

**Comment by andrey-tech** [comment]
@tvbeek 

Hello! Do you have any plan for release date? We all really wait for PHP 8.4 support for now.

**Comment by AJenbo** [comment]
You can already use the 3.x-dev version for running on PHP 8.4

**Comment by AJenbo** [comment]
Implementations for the PHP 8.4 and 8.5 features are now in review. The hope is to have everything in line for a release before the end of the year. Major missing part is parallel processing (being worked on here https://github.com/pdepend/pdepend/pull/877).

**Comment by AJenbo** [comment]
I think 3.x is ready now, please feel free to test it out and let us know if you think there are any regressions or other things that needs to be dealt with before it's released as the next stable version: https://github.com/pdepend/pdepend/tree/3.x

**Comment by derwassi** [comment]
it seems there's is a regression.
attributes on constructor arguments seem to fail:
e.g.:
```
class SomeClass extends AnotherClass
{
    public function __construct(#[Autowire(service: 'myService')] protected InjectedClass $dependency)
    {
    }
}
```
leads to an error like this
```
ERROR while parsing 
--------------------
Unexpected token: protected, line: 32, col: 9, file: /var/www/html/SomeClass.php.
#0 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(8863): PDepend\Source\Parser\UnexpectedTokenException->__construct()
#1 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(8850): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(8819): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedNextTokenException()
#3 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(7981): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken()
#4 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(6821): PDepend\Source\Language\PHP\AbstractPHPParser->parseVariableDeclarator()
#5 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(6587): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameter()
#6 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(6569): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameterFromType()
#7 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(6464): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameterOrTypeHintOrByReference()
#8 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(6521): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameterOrPrefix()
#9 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1780): PDepend\Source\Language\PHP\AbstractPHPParser->parseFormalParameters()
#10 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1742): PDepend\Source\Language\PHP\AbstractPHPParser->parseCallableDeclaration()
#11 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1477): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodDeclaration()
#12 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1316): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration()
#13 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1123): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody()
#14 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(7231): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
#15 /var/www/html/vendor/pdepend/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(745): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#16 /var/www/html/vendor/pdepend/pdepend/src/Engine.php(654): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#17 /var/www/html/vendor/pdepend/pdepend/src/Engine.php(561): PDepend\Engine->parseFile()
#18 /var/www/html/vendor/pdepend/pdepend/src/Engine.php(520): PDepend\Engine->runWorker()
#19 /var/www/html/vendor/pdepend/pdepend/src/Engine.php(300): PDepend\Engine->performParseProcess()
#20 /var/www/html/vendor/pdepend/pdepend/src/TextUI/Runner.php(294): PDepend\Engine->analyze()
#21 /var/www/html/vendor/pdepend/pdepend/src/TextUI/Command.php(251): PDepend\TextUI\Runner->run()
#22 /var/www/html/vendor/pdepend/pdepend/src/TextUI/Command.php(616): PDepend\TextUI\Command->run()
#23 /var/www/html/vendor/pdepend/pdepend/bin/pdepend(72): PDepend\TextUI\Command::main()
#24 {main}

```
The last commit where it worked is f46a36b5eec7c6dd82e0c2df11294a49be9d2a80

**Comment by andrey-tech** [comment]
@AJenbo Thanks for your big work on this project! Do you have roadmap on 2026 year?

**Comment by AJenbo** [comment]
@andrey-tech thanks. Yes, 3.0.0 release should happen March, I'm currently finishing up some pressing work related tasks and will return to OSS after that.

**Comment by n0099** [comment]
It's April now...

**Comment by AJenbo** [comment]
Sorry, last week got a bit packed.started working on things yesterday.

**Comment by FeBe95** [comment]
@AJenbo No need to apologize! We're all volunteers in the open-source community and know how it goes. Looking forward to version 3.x whenever it's ready!

**Comment by AJenbo** [comment]
I think https://github.com/pdepend/pdepend/pull/953 is the last needed bit for Pdepend 3.0.0
But we will probably still wait with the release until we feel equality confident about PHPMD. I'm currently working on finishing the planned bits for it.
